### ISSUE TITLE
Epic: Auth-Layer sub project 

### ISSUE THREAD

**Issue by AlfredoG87** [hashgraph/hedera-the-graph#18]
### Problem

In order to offer a hosted graph-node for Hedera community projects, the dev team of such projects will need to create, deploy and test their own subgraphs, for that they need to have access to the `admin` port of our indexer instance of the graph-node, but in order to authorize dev teams to create and deploy to their sub-graphs but not to other subgraphs, we need to have in place an auth layer.

### Solution

Create a custom service for Auth-Layer based on the Design described [here](https://github.com/hashgraph/hedera-the-graph/pull/16/files?short_path=172eda8#diff-172eda819d380ebab5320cc9073d9040954fa4d856ca30f914167d27a2bcb686).

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-the-graph/issues/19
- [ ] https://github.com/hashgraph/hedera-the-graph/issues/20
- [ ] https://github.com/hashgraph/hedera-the-graph/issues/21
- [ ] https://github.com/hashgraph/hedera-the-graph/issues/24
- [ ] https://github.com/hashgraph/hedera-the-graph/issues/49
- [ ] https://github.com/hashgraph/hedera-the-graph/issues/48
- [ ] https://github.com/hashgraph/hedera-the-graph/issues/22
- [ ] https://github.com/hashgraph/hedera-the-graph/issues/56
```

### References

Ethers V6 SDK Issue - https://github.com/hashgraph/hedera-sdk-js/issues/1615
Solidity-coverage - https://github.com/hashgraph/hedera-json-rpc-relay/issues/416
