### ISSUE TITLE
Auth-Layer: EnvoyProxy POC

### ISSUE THREAD

**Issue by AlfredoG87** [hashgraph/hedera-the-graph#24]
```[tasklist]
### Tasks
- [x] Validate is a valid Json
- [x] Extract Token, method and params
- [x] Check Token on Postgres DB
- [x] Check Token on Redis
- [x] Push PR for Reviews
```

**Comment by AlfredoG87** [comment]
POC is finished.
