### ISSUE TITLE
TheGraph Auth-Layer Deployment on Production Environments

### ISSUE THREAD

**Issue by AlfredoG87** [hashgraph/hedera-the-graph#56]
```[tasklist]
### Tasks
- [x] Deployment on DevOps Test Environment
- [x] E2E Test on DevOps Test Environment
- [x] Deployment on Previewnet
- [x] E2E Test on Previewnet
- [x] Deployment on Testnet
- [x] E2E Test on Testnet
- [x] Deployement on Mainnet
- [x] E2E Test on Mainnet
- [ ] https://github.com/hashgraph/hedera-the-graph/issues/64
```
