### ISSUE TITLE
Configure SMTP and Test email features

### ISSUE THREAD

**Issue by AlfredoG87** [hashgraph/hedera-the-graph#64]
```[tasklist]
### Tasks
- [x] Configure SMTP for Previewnet
- [x] Test Email features for Previewnet
- [x] Configure SMTP for Testnet
- [x] Test Email features for Testnet
- [x] Configure SMTP for Mainnet
- [x] Test Email features for Mainnet
```
